import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import Topbar from "./components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-7 grid-rows-6 min-h-screen">
          <div className=" row-end-7 row-start-1 border-gray-200 border-r">
            <Sidebar />
          </div>
          <div className="col-start-2 col-end-8">
            <Topbar />
          </div>
          <div className="row-start-2 row-end-7 col-start-2 col-end-8 bg--700 ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
